// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  product_grid: dynamic(() => import("./ProductGrid")),
  team_grid: dynamic(() => import("./TeamGrid")),
  text_image: dynamic(() => import("./TextImage")),
  video_block: dynamic(() => import("./VideoBlock")),
};
